phraseapp:
  access_token: a399278d51e154f5ad1bb20e6fee751a95be9acf4fdf143108419ffb7ecedd6c
  file_format: xml
  project_id: 3be76832316c805973fa2b46c0db1de4
  pull:
    targets:
    - file: ./mobile/src/main/res/values-de/strings.xml
      params:
        tag: porsche-app-framework
        locale_id: e1ce05a03c0a444c0c7d51fbf64abe28
        format_options:
          enclose_in_cdata: true
          convert_placeholders: true
    - file: ./mobile/src/main/res/values/strings.xml
      params:
        tag: porsche-app-framework
        locale_id: 92ecf85f6f7e8de937e63da7242a5a2b
        format_options:
          enclose_in_cdata: true
          convert_placeholders: true
    - file: ./mobile/src/main/res/values-de-rCH/strings.xml
      params:
        tag: porsche-app-framework
        locale_id: b53cfd7d439fbc98e94a8d8f1db6ad36
        format_options:
          enclose_in_cdata: true
          convert_placeholders: true
  push:
    sources:
    - file: ./mobile/src/main/res/values/strings.xml
      params: {locale_id: 3be76832316c805973fa2b46c0db1de4}
